# Generated by Django 2.2 on 2020-02-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
