name: msa_recommender
description: MSA Recommender App for Students.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dynamic_theme: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  fonts:
  - family: Fondamento
    fonts:
    - asset: assets/fonts/Fondamento-Regular.ttf
  - family: Dekko
    fonts:
      - asset: assets/fonts/Dekko-Regular.ttf
  uses-material-design: true

